package data.hullmods;

import java.util.HashMap;
import java.util.Map;

import com.fs.starfarer.api.combat.BaseHullMod;
import com.fs.starfarer.api.combat.MutableShipStatsAPI;
import com.fs.starfarer.api.combat.ShipAPI;
import com.fs.starfarer.api.combat.ShipAPI.HullSize;
import com.fs.starfarer.api.ui.TooltipMakerAPI;
import com.fs.starfarer.api.util.Misc;

@SuppressWarnings("unchecked")
public class FluxDistributor extends BaseHullMod {
	
	public static float FLUX_COST_MULT = .96f;

	private static Map mag = new HashMap();
	static {
		mag.put(HullSize.FRIGATE, 30f);
		mag.put(HullSize.DESTROYER, 60f);
		mag.put(HullSize.CRUISER, 90f);
		mag.put(HullSize.CAPITAL_SHIP, 150f);
	}
	
	public void applyEffectsBeforeShipCreation(HullSize hullSize, MutableShipStatsAPI stats, String id) {
		if (stats.getVariant().getSMods().contains("fluxdistributor") || stats.getVariant().getHullSpec().isBuiltInMod("fluxdistributor")) {
			stats.getEnergyWeaponFluxCostMod().modifyMult(id, FLUX_COST_MULT);
			stats.getBallisticWeaponFluxCostMod().modifyMult(id, FLUX_COST_MULT);
		}
		stats.getFluxDissipation().modifyFlat(id, (Float) mag.get(hullSize));
	}
	
	public String getDescriptionParam(int index, HullSize hullSize) {
		if (index == 0) return "" + ((Float) mag.get(HullSize.FRIGATE)).intValue();
		if (index == 1) return "" + ((Float) mag.get(HullSize.DESTROYER)).intValue();
		if (index == 2) return "" + ((Float) mag.get(HullSize.CRUISER)).intValue();
		if (index == 3) return "" + ((Float) mag.get(HullSize.CAPITAL_SHIP)).intValue();
		return null;
	}

    public void addPostDescriptionSection(TooltipMakerAPI tooltip, ShipAPI.HullSize hullSize, ShipAPI ship, float width, boolean isForModSpec) {
		if (isForModSpec) {
			tooltip.addPara("S-mod Bonus: %s flux generated by energy and ballistic weapons", 10f, Misc.getGrayColor(), Misc.getHighlightColor(), "-4" + "%");
			return;
		} else if (ship.getMutableStats().getVariant().getSMods().contains("fluxdistributor")) {
			tooltip.addPara("S-mod Bonus: %s flux generated by energy and ballistic weapons", 10f, Misc.getPositiveHighlightColor(), Misc.getHighlightColor(), "-4" + "%");
		} else if (ship.getHullSpec().isBuiltInMod("fluxdistributor")) {
			tooltip.addPara("S-mod Bonus: %s flux generated by energy and ballistic weapons", 10f, Misc.getPositiveHighlightColor(), Misc.getHighlightColor(), "-4" + "%");
        } else if (!isForModSpec) {
			tooltip.addPara("S-mod Bonus: %s flux generated by energy and ballistic weapons", 10f, Misc.getGrayColor(), Misc.getHighlightColor(), "-4" + "%");
		}
    }

}
